version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "1234:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    restart: always

  webapp:
    build:
      context: https://github.com/zipben/reverse-proxy.git
      dockerfile: webapp/Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./nginx/conf.d:/nginx/conf.d
    network_mode: host
    restart: always 