version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "1234:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./webapp:/app
      - ./nginx/conf.d:/nginx/conf.d
    network_mode: host 